[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["matriz windowsboy111 <cyruschan111@outlook.com>"]
description = ""
name = "discord-bot-kccs-official"
version = "0.1.0"
[tool.poetry.dependencies]
discord = "^1.0"
flask = "^1.1"
mcstatus = "^3.1"
python = "^3.7"
python-dotenv = "^0.13.0"
py-mini-racer = "^0.2.0"
[tool.poetry.dev-dependencies]
